# This is the configuration used to check the rubocop source code.

AllCops:
  Exclude:
  - '**/env.rb'

################## Customized rules ##################

Metrics/LineLength:
  Max: 150

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Max: 30

Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true

# Waiting for answer regarding snake_case or kebab-case use in FileNames
Style/FileName:
  Enabled: false

# Investigate Carriage error
EndOfLine:
  Enabled: false