# This is the configuration used to check the rubocop source code.

AllCops:
  Exclude:
  # Currently excluded for future investigation
    - '**/hooks.rb'
    - '**/env.rb'
    - '**/http_util.rb'
    - 'features/step_definitions/helpers/table_transform.rb'

################## Customized rules ##################

Metrics/LineLength:
  Max: 150
  Exclude:
    - '**/long-text.rb'

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Max: 30

Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true

# Waiting for answer regarding snake_case or kebab-case use in FileNames
Style/FileName:
  Enabled: false

# Investigate Carriage error
EndOfLine:
  Enabled: false