source 'https://rubygems.org'

gem 'cucumber', '=2.4.0'
gem 'httparty'
gem 'rspec', '>=3.4'
gem 'rspec-expectations', '=3.4.0'
gem 'rake', '10.4.0'
gem 'parallel_tests'
gem 'jsonpath'
gem 'report_builder', '=0.1.4'
